export const ProjectData = [
  {
    "projectID": "1",
    "projectName": "Netflix Clone-UI",
    "projectDesc": "This is a Netflix UI Clone",
    "techUsed": ["HTML", "CSS3", "JavaScript"],
    "repoLink": "https://github.com/Abhijit47/Netflix-UI-Clone-Pure-HTML-and-CSS3.git",
    "liveLink": "https://clone-nf-app.netlify.app",
    "imageID": "1",
    "imageURL": require(`../../assets/project_images/project1.PNG`),
  },
  {
    "projectID": "2",
    "projectName": "Amazon Clone-UI",
    "projectDesc": "This is an Amazon UI Clone",
    "techUsed": ["HTML", "CSS3", "Bootstrap 5", "JavaScript"],
    "repoLink": "https://github.com/Abhijit47/Amazon-clone-Frontend-UI.git",
    "liveLink": "https://amazone-ui-clone.netlify.app",
    "imageID": "2",
    "imageURL": require(`../../assets/project_images/project2.PNG`),
  },
  {
    "projectID": "3",
    "projectName": "Zomato UI Clone",
    "projectDesc": "This is a Zomato UI Clone.",
    "techUsed": ["HTML", "CSS3", "Bootstrap 5"],
    "repoLink": "https://github.com/Abhijit47/Zomato-UI-with-Bootstrap-5.git",
    "liveLink": "https://zomato-ui-v3.netlify.app",
    "imageID": "3",
    "imageURL": require(`../../assets/project_images/project3.PNG`),
  },
  {
    "projectID": "4",
    "projectName": "Let's food App",
    "projectDesc": "Online food delivery app.",
    "techUsed": ["HTML", "CSS3"],
    "repoLink": "https://github.com/Abhijit47/Fullstack-Web-dev-Assignment/tree/master/assignment%2014",
    "liveLink": "https://letsfoodapp.netlify.app",
    "imageID": "4",
    "imageURL": require(`../../assets/project_images/project4.PNG`),
  },
  {
    "projectID": "5",
    "projectName": "GitHub User's & Repos",
    "projectDesc": "Getting Github users and their Repos.",
    "techUsed": ["HTML", "CSS3", "Bootstrap 5", "JavaScript"],
    "repoLink": "https://github.com/Abhijit47/GitHub-API.git",
    "liveLink": "https://githubapiwithdom.netlify.app",
    "imageID": "5",
    "imageURL": require(`../../assets/project_images/project5.PNG`),
  },
  {
    "projectID": "6",
    "projectName": "JS Dom and Event",
    "projectDesc": "An example of JS DOM and Events.",
    "techUsed": ["HTML", "CSS3", "Bootstrap 5", "JavaScript"],
    "repoLink": "https://github.com/Abhijit47/Dom-and-Event.git",
    "liveLink": "https://dom-n-events.netlify.app",
    "imageID": "6",
    "imageURL": require(`../../assets/project_images/project6.PNG`),
  },
  {
    "projectID": "7",
    "projectName": "Random Brewery Data",
    "projectDesc": "Get random brewery data.",
    "techUsed": ["HTML", "CSS3", "Bootstrap 5", "JavaScript"],
    "repoLink": "https://github.com/Abhijit47/Random-Brewrey-Data.git",
    "liveLink": "https://randombrewerydata.netlify.app",
    "imageID": "7",
    "imageURL": require(`../../assets/project_images/project7.PNG`),
  },
  {
    "projectID": "8",
    "projectName": "Resume Template Design",
    "projectDesc": "This a resume template design.",
    "techUsed": ["HTML", "CSS3"],
    "repoLink": "https://github.com/Abhijit47/Fullstack-Web-dev-Assignment/tree/03d82aab6929fa9799261228868f6df5b2efac8d/assignment%208",
    "liveLink": "https://myresume-v1.netlify.app",
    "imageID": "8",
    "imageURL": require(`../../assets/project_images/project8.PNG`),
  },
  {
    "projectID": "9",
    "projectName": "Lamborgini landing page",
    "projectDesc": "Lamborgini landing page design.",
    "techUsed": ["HTML", "CSS3", "JavaScript"],
    "repoLink": "https://github.com/Abhijit47/Fullstack-Web-dev-Assignment/tree/03d82aab6929fa9799261228868f6df5b2efac8d/assignment%2015",
    "liveLink": "https://lamborgini-landing-page.netlify.app",
    "imageID": "9",
    "imageURL": require(`../../assets/project_images/project9.PNG`),
  },
  {
    "projectID": "10",
    "projectName": "Portfolio template design",
    "projectDesc": "Portfolio template pure Bootstrap.",
    "techUsed": ["HTML", "CSS3", "Bootstrap 5", "JavaScript"],
    "repoLink": "https://github.com/Abhijit47/bootstarp-practice.git",
    "liveLink": "https://friendly-torte-f6217b.netlify.app",
    "imageID": "10",
    "imageURL": require(`../../assets/project_images/project10.PNG`),
  },
  {
    "projectID": "11",
    "projectName": "Portfolio with Bootstrap 5",
    "projectDesc": "This is my portfolio with BS 5.",
    "techUsed": ["HTML", "CSS3", "Bootstrap 5"],
    "repoLink": "https://github.com/Abhijit47/My-Portfolio-Bootstrap-5.git",
    "liveLink": "https://abhijitdevportfolio.netlify.app",
    "imageID": "11",
    "imageURL": require(`../../assets/project_images/project11.PNG`),
  },
  {
    "projectID": "12",
    "projectName": "Another Bootstrap 5 Layout",
    "projectDesc": "Example of bootstrap 5 layout.",
    "techUsed": ["HTML", "CSS3", "Bootstrap 5"],
    "repoLink": "https://github.com/Abhijit47/Pure-Bootstrap-Layout.git",
    "liveLink": "https://super-crisp-e4924b.netlify.app",
    "imageID": "12",
    "imageURL": require(`../../assets/project_images/project12.PNG`),
  },
  {
    "projectID": "13",
    "projectName": "Astronomy Picture of the Day",
    "projectDesc": "Get Astronomy Picture of the Day.",
    "techUsed": ["HTML", "CSS3", "JavaScript"],
    "repoLink": "https://github.com/Abhijit47/Nasa-APOD-private-.git",
    "liveLink": "https://nasa-apod-v2.netlify.app",
    "imageID": "13",
    "imageURL": require(`../../assets/project_images/project13.PNG`),
  },
  {
    "projectID": "14",
    "projectName": "Anime Movie Details",
    "projectDesc": "Get Anime Movie Details.",
    "techUsed": [
      "HTML",
      "CSS33",
      "Bootstrap 5",
      "JavaScript"
    ],
    "repoLink": "https://github.com/Abhijit47/Jikan-Anime-API.git",
    "liveLink": "https://animeapiwithdom.netlify.app",
    "imageID": "14",
    "imageURL": require(`../../assets/project_images/project14.PNG`),
  },
  {
    "projectID": "15",
    "projectName": "Nationalize API (JS-DOM)",
    "projectDesc": "Predict the nationality of a name.",
    "techUsed": [
      "HTML",
      "CSS33",
      "Bootstrap 5",
      "JavaScript"
    ],
    "repoLink": "https://github.com/Abhijit47/JS-Nationalize.git",
    "liveLink": "https://nationalizeapiwithdom.netlify.app",
    "imageID": "15",
    "imageURL": require(`../../assets/project_images/project15.PNG`),
  },
  {
    "projectID": "16",
    "projectName": "Country details with Weather",
    "projectDesc": "Get weather details of each country.",
    "techUsed": [
      "HTML",
      "CSS33",
      "Bootstrap 5",
      "JavaScript"
    ],
    "repoLink": "https://github.com/Abhijit47/Rest-Country-Weather-v2.git",
    "liveLink": "https://restcountryweather-v2.netlify.app",
    "imageID": "16",
    "imageURL": require(`../../assets/project_images/project16.PNG`),
  },
  {
    "projectID": "17",
    "projectName": "Pokemon API (JS DOM)",
    "projectDesc": "Get some Pokemon details.",
    "techUsed": [
      "HTML",
      "CSS33",
      "Bulma CSS3",
      "JavaScript"
    ],
    "repoLink": "https://github.com/Abhijit47/Poke-API-with-fetch-Async-Await-.git",
    "liveLink": "https://pokeapiasync.netlify.app",
    "imageID": "17",
    "imageURL": require(`../../assets/project_images/project17.PNG`),
  },
  {
    "projectID": "18",
    "projectName": "Random user with DOM",
    "projectDesc": "Get random user with details.",
    "techUsed": [
      "HTML",
      "CSS33",
      "Bootstarp 5",
      "JavaScript"
    ],
    "repoLink": "https://github.com/Abhijit47/Asyncrhonous-Programming-with-Fetch-API.git",
    "liveLink": "https://fetchapidemo.netlify.app",
    "imageID": "18",
    "imageURL": require(`../../assets/project_images/project18.PNG`),
  },
  // React
  {
    "projectID": "19",
    "projectName": "Movie search with DOM",
    "projectDesc": "Get random movies with DOM.",
    "techUsed": [
      "HTML",
      "Bootstarp 5",
      "React JS"
    ],
    "repoLink": "https://github.com/Abhijit47/React-Movie-Cards.git",
    "liveLink": "https://dreamy-mousse-c3f3b8.netlify.app",
    "imageID": "19",
    "imageURL": require(`../../assets/project_images/project19.PNG`),
  },

  {
    "projectID": "20",
    "projectName": "Simple Price card",
    "projectDesc": "Example of multiple price cards.",
    "techUsed": [
      "HTML",
      "Bootstarp 5",
      "React JS"
    ],
    "repoLink": "https://github.com/Abhijit47/React_Price_Cards.git",
    "liveLink": "https://statuesque-begonia-9d22da.netlify.app",
    "imageID": "20",
    "imageURL": require(`../../assets/project_images/project20.PNG`),
  },
  {
    "projectID": "21",
    "projectName": "E-commerce checkout page",
    "projectDesc": "Example of E-commerce checkout page.",
    "techUsed": [
      "HTML",
      "CSS33",
      "React JS"
    ],
    "repoLink": "https://github.com/Abhijit47/React-Checkout-Page.git",
    "liveLink": "https://react-ecom-checkout-page.netlify.app",
    "imageID": "21",
    "imageURL": require(`../../assets/project_images/project21.PNG`),
  },
  {
    "projectID": "22",
    "projectName": "React form Validation",
    "projectDesc": "Simple Form validation.",
    "techUsed": [
      "HTML",
      "Bootstarp 5",
      "React JS"
    ],
    "repoLink": "https://github.com/Abhijit47/react-form-validation.git",
    "liveLink": "https://react-form-validation-sage.vercel.app",
    "imageID": "22",
    "imageURL": require(`../../assets/project_images/project22.PNG`),
  },
  {
    "projectID": "23",
    "projectName": "React Text Analyzer",
    "projectDesc": "Simple text anlyzer with react.",
    "techUsed": [
      "HTML",
      "Bootstarp 5",
      "React JS"
    ],
    "repoLink": "https://github.com/Abhijit47/React-Text-Analyzer.git",
    "liveLink": "https://react-text-analyzer.vercel.app",
    "imageID": "23",
    "imageURL": require(`../../assets/project_images/project23.PNG`),
  },
  {
    "projectID": "24",
    "projectName": "React Currency converter",
    "projectDesc": "Simple currency converter react.",
    "techUsed": [
      "HTML",
      "Bootstarp 5",
      "React JS"
    ],
    "repoLink": "https://github.com/Abhijit47/React-simple-currency-calculator.git",
    "liveLink": "https://react-simple-currency-calculator.vercel.app",
    "imageID": "24",
    "imageURL": require(`../../assets/project_images/project24.PNG`),
  },
  {
    "projectID": "25",
    "projectName": "React CRUD App",
    "projectDesc": "Simple CRUD with Mock User.",
    "techUsed": [
      "HTML",
      "Bootstarp 5",
      "React JS",
      "React Router 6"
    ],
    "repoLink": "https://github.com/Abhijit47/React-CRUD-App.git",
    "liveLink": "https://magnificent-taiyaki-c01b68.netlify.app",
    "imageID": "25",
    "imageURL": require(`../../assets/project_images/project25.PNG`),
  },
  {
    "projectID": "26",
    "projectName": "AirBnB Clone UI",
    "projectDesc": "This a Clone of AirBnB UI.",
    "techUsed": [
      "HTML",
      "Bootstarp 5",
      "React JS",
      "React Router 6"
    ],
    "repoLink": "https://github.com/Abhijit47/Airbnb-Clone.git",
    "liveLink": "https://starlit-palmier-0c861b.netlify.app",
    "imageID": "26",
    "imageURL": require(`../../assets/project_images/project26.PNG`),
  },
  //fs
  {
    "projectID": "27",
    "projectName": "User Authentication App",
    "projectDesc": "Login and Register a valid user.",
    "techUsed": [
      "HTML",
      "Bootstarp 5",
      "React JS",
      "Node JS",
      "JWT",
      "Bcrypt",
      "MongoDB"
    ],
    "repoLink": "https://github.com/Abhijit47/User-Authentication-app-frontend.git",
    "liveLink": "https://user-auth-app.vercel.app",
    "imageID": "27",
    "imageURL": require(`../../assets/project_images/project27.PNG`),
  },
  {
    "projectID": "28",
    "projectName": "Pokemon App",
    "projectDesc": "Pokemon app with User Auth.",
    "techUsed": [
      "HTML",
      "Bootstarp 5",
      "React JS",
      "Node JS",
      "JWT",
      "Bcrypt",
      "MongoDB"
    ],
    "repoLink": "https://github.com/Abhijit47/pokemon_app_frontend.git",
    "liveLink": "https://pokemon-app-frontend-mu.vercel.app",
    "imageID": "28",
    "imageURL": require(`../../assets/project_images/project28.PNG`),
  },
  {
    "projectID": "29",
    "projectName": "Auth & Authorization",
    "projectDesc": "This is an user authentication app.",
    "techUsed": [
      "React-JS",
      "MUI",
      "Materialized CSS3",
      "Node-JS",
      "JWT",
      "BCrypt"
    ],
    "repoLink": "https://github.com/Abhijit47/User-Auth-n-Authentication-Frontend.git",
    "liveLink": "https://user-auth-n-authentication-e0uk6y7e6-abhijit47.vercel.app/login",
    "imageID": "29",
    "imageURL": require(`../../assets/project_images/project29.PNG`),
  },
  {
    "projectID": "30",
    "projectName": "Admin Panel Layout-1",
    "projectDesc": "Static Admin Dashboard Layout.",
    "techUsed": [
      "HTML",
      "CSS33",
      "JavaScript"
    ],
    "repoLink": "https://github.com/Abhijit47/Admin-Dashboard-frontend.git",
    "liveLink": "https://admin-panel-v1.netlify.app",
    "imageID": "30",
    "imageURL": require(`../../assets/project_images/project30.PNG`),
  },
  {
    "projectID": "31",
    "projectName": "Admin Panel Layout-2",
    "projectDesc": "Admin Dashboard Layout with Charts.",
    "techUsed": [
      "HTML",
      "CSS33",
      "JavaScript",
      "Apex Chart"
    ],
    "repoLink": "https://github.com/Abhijit47/Admin-Dashboard-with-chart.git",
    "liveLink": "https://admin-panel-layout-v2.netlify.app",
    "imageID": "31",
    "imageURL": require(`../../assets/project_images/project31.PNG`),
  },
  {
    "projectID": "32",
    "projectName": "Admin Panel Layout-v2",
    "projectDesc": "Admin Dashboard Layout with Charts.",
    "techUsed": [
      "HTML",
      "CSS33",
      "React JS",
      "Apex Chart"
    ],
    "repoLink": "https://github.com/Abhijit47/Admin-Dashboard-React-with-Charts.git",
    "liveLink": "https://resonant-zuccutto-99980d.netlify.app",
    "imageID": "32",
    "imageURL": require(`../../assets/project_images/project32.PNG`),
  },
  {
    "projectID": "33",
    "projectName": "Firebase Auth System",
    "projectDesc": "Login and Register with oAuth.",
    "techUsed": [
      "HTML",
      "CSS33",
      "React JS",
      "Firebase"
    ],
    "repoLink": "https://github.com/Abhijit47/React_Firebase_Authentication_App.git",
    "liveLink": "https://react-firebase-auth-zeta.vercel.app",
    "imageID": "33",
    "imageURL": require(`../../assets/project_images/project33.PNG`),
  }
];